spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  #JPA Settings

  jpa:
    hibernate:
      ddl-auto: update  #create - drop and recreate


management:
  endpoints:
    web:
      exposure:
        #include: "*" # Include everything
        include: "health,beans,metrics"
        exclude: "caches"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

# Debugging in terminal, you can comment those
#logging:
 # level:
  #  com.project.rest_demo.controller: DEBUG
   # root: DEBUG
